-- 0004: 種目カタログ拡充(フリーウェイト+マシン定番。生成: tools/gen-exercise-catalog.mjs)
-- INSERT OR IGNORE: 既存 id(0002 seed / backfill)は温存。
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('dumbbell-bench-press','Dumbbell Bench Press','ダンベルベンチプレス','compound','dumbbell','horizontal_press','bilateral','per_limb',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-bench-press','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-bench-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-bench-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('incline-barbell-bench-press','Incline Barbell Bench Press','インクラインベンチプレス','compound','barbell','incline_press','bilateral','total',0,'6-10','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-barbell-bench-press','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-barbell-bench-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-barbell-bench-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('incline-dumbbell-press','Incline Dumbbell Press','インクラインダンベルプレス','compound','dumbbell','incline_press','bilateral','per_limb',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-dumbbell-press','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-dumbbell-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('incline-dumbbell-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('dumbbell-fly','Dumbbell Fly','ダンベルフライ','isolation','dumbbell','horizontal_adduction','bilateral','per_limb',0,'10-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-fly','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-fly','front_delts','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('cable-crossover','Cable Crossover','ケーブルクロスオーバー','isolation','cable','horizontal_adduction','bilateral','per_limb',0,'12-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('cable-crossover','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('cable-crossover','front_delts','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('machine-chest-press','Machine Chest Press','マシンチェストプレス','compound','machine','horizontal_press','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-chest-press','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-chest-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-chest-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('push-up','Push-Up','プッシュアップ','compound','bodyweight','horizontal_press','bilateral','total',1,'10-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('push-up','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('push-up','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('push-up','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hs-iso-incline-press','Hammer Strength Iso-Lateral Incline Press','アイソラテラルインクラインプレス','compound','machine','incline_press','unilateral','per_side',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-incline-press','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-incline-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-incline-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hs-iso-wide-chest','Hammer Strength Iso-Lateral Wide Chest','アイソラテラルワイドチェスト','compound','machine','horizontal_press','unilateral','per_side',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-chest','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-chest','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-chest','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('pec-deck-fly','Machine Pec Fly (Pec Deck)','ペックフライ','isolation','machine','horizontal_adduction','bilateral','total',0,'12-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('pec-deck-fly','chest','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('pec-deck-fly','front_delts','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('barbell-row','Barbell Bent-Over Row','ベントオーバーロウ','compound','barbell','horizontal_pull','bilateral','total',0,'6-10','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-row','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-row','traps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-row','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-row','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-row','lower_back','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('dumbbell-row','One-Arm Dumbbell Row','ワンハンドダンベルロウ','compound','dumbbell','horizontal_pull','unilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-row','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-row','traps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-row','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-row','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('t-bar-row','T-Bar Row','ティーバーロー','compound','barbell','horizontal_pull','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('t-bar-row','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('t-bar-row','traps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('t-bar-row','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('t-bar-row','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('t-bar-row','lower_back','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('seated-cable-row','Seated Cable Row','シーテッドロウ','compound','cable','horizontal_pull','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('seated-cable-row','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('seated-cable-row','traps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('seated-cable-row','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('seated-cable-row','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('pull-up','Pull-Up','プルアップ(懸垂)','compound','bodyweight','vertical_pull','bilateral','total',1,'5-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('pull-up','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('pull-up','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('pull-up','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('chin-up','Chin-Up','チンアップ','compound','bodyweight','vertical_pull','bilateral','total',1,'5-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('chin-up','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('chin-up','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('face-pull','Face Pull','フェイスプル','isolation','cable','horizontal_pull','bilateral','total',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('face-pull','rear_delts','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('face-pull','traps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('straight-arm-pulldown','Straight-Arm Pulldown','ストレートアームプルダウン','isolation','cable','vertical_pull','bilateral','total',0,'12-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('straight-arm-pulldown','lats','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hs-iso-wide-pulldown','Hammer Strength Iso-Lateral Wide Pulldown','アイソラテラルワイドプルダウン','compound','machine','vertical_pull','unilateral','per_side',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-pulldown','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-pulldown','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-wide-pulldown','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hs-iso-low-row','Hammer Strength Iso-Lateral Low Row','アイソラテラルローロウ','compound','machine','horizontal_pull','unilateral','per_side',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-low-row','lats','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-low-row','traps','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-low-row','rear_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hs-iso-low-row','biceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('overhead-press','Overhead Press','オーバーヘッドプレス','compound','barbell','vertical_press','bilateral','total',0,'5-8','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('overhead-press','front_delts','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('overhead-press','side_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('overhead-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('dumbbell-shoulder-press','Dumbbell Shoulder Press','ダンベルショルダープレス','compound','dumbbell','vertical_press','bilateral','per_limb',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-shoulder-press','front_delts','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-shoulder-press','side_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-shoulder-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('arnold-press','Arnold Press','アーノルドプレス','compound','dumbbell','vertical_press','bilateral','per_limb',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('arnold-press','front_delts','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('arnold-press','side_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('arnold-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('lateral-raise','Dumbbell Lateral Raise','サイドレイズ','isolation','dumbbell','abduction','bilateral','per_limb',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('lateral-raise','side_delts','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('cable-lateral-raise','Cable Lateral Raise','ケーブルサイドレイズ','isolation','cable','abduction','unilateral','total',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('cable-lateral-raise','side_delts','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('rear-delt-fly','Rear Delt Fly','リアレイズ','isolation','dumbbell','horizontal_abduction','bilateral','per_limb',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('rear-delt-fly','rear_delts','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('machine-shoulder-press','Machine Shoulder Press','マシンショルダープレス','compound','machine','vertical_press','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-shoulder-press','front_delts','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-shoulder-press','side_delts','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('machine-shoulder-press','triceps','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('barbell-curl','Barbell Curl','バーベルカール','isolation','barbell','elbow_flexion','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-curl','biceps','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('barbell-curl','forearms','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('dumbbell-curl','Dumbbell Curl','ダンベルカール','isolation','dumbbell','elbow_flexion','bilateral','per_limb',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-curl','biceps','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('dumbbell-curl','forearms','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hammer-curl','Hammer Curl','ハンマーカール','isolation','dumbbell','elbow_flexion','bilateral','per_limb',0,'10-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hammer-curl','biceps','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hammer-curl','forearms','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('preacher-curl','Preacher Curl','プリーチャーカール','isolation','machine','elbow_flexion','bilateral','total',0,'10-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('preacher-curl','biceps','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('cable-curl','Cable Curl','ケーブルカール','isolation','cable','elbow_flexion','bilateral','total',0,'10-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('cable-curl','biceps','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('triceps-pushdown','Triceps Pushdown','トライセプスプレスダウン','isolation','cable','elbow_extension','bilateral','total',0,'10-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('triceps-pushdown','triceps','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('overhead-triceps-extension','Overhead Triceps Extension','オーバーヘッドエクステンション','isolation','dumbbell','elbow_extension','bilateral','total',0,'10-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('overhead-triceps-extension','triceps','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('skull-crusher','Skull Crusher','スカルクラッシャー','isolation','barbell','elbow_extension','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('skull-crusher','triceps','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('close-grip-bench-press','Close-Grip Bench Press','ナローベンチプレス','compound','barbell','horizontal_press','bilateral','total',0,'6-10','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('close-grip-bench-press','triceps','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('close-grip-bench-press','chest','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('close-grip-bench-press','front_delts','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('back-squat','Barbell Back Squat','バーベルスクワット','compound','barbell','squat','bilateral','total',0,'5-8','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('back-squat','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('back-squat','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('back-squat','hamstrings','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('back-squat','lower_back','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('front-squat','Front Squat','フロントスクワット','compound','barbell','squat','bilateral','total',0,'5-8','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('front-squat','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('front-squat','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('front-squat','abs','stabilizer',0.25);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('leg-press','Leg Press','レッグプレス','compound','machine','squat','bilateral','total',0,'8-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('leg-press','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('leg-press','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('leg-press','hamstrings','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hack-squat','Hack Squat','ハックスクワット','compound','machine','squat','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hack-squat','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hack-squat','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('romanian-deadlift','Romanian Deadlift','ルーマニアンデッドリフト','compound','barbell','hinge','bilateral','total',0,'6-10','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('romanian-deadlift','hamstrings','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('romanian-deadlift','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('romanian-deadlift','lower_back','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('leg-extension','Leg Extension','レッグエクステンション','isolation','machine','knee_extension','bilateral','total',0,'12-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('leg-extension','quads','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('leg-curl','Leg Curl','レッグカール','isolation','machine','knee_flexion','bilateral','total',0,'10-15','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('leg-curl','hamstrings','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('bulgarian-split-squat','Bulgarian Split Squat','ブルガリアンスクワット','compound','dumbbell','lunge','unilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('bulgarian-split-squat','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('bulgarian-split-squat','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('bulgarian-split-squat','hamstrings','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('walking-lunge','Walking Lunge','ウォーキングランジ','compound','dumbbell','lunge','unilateral','total',0,'10-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('walking-lunge','quads','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('walking-lunge','glutes','secondary',0.5);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('walking-lunge','hamstrings','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('calf-raise','Calf Raise','カーフレイズ','isolation','machine','ankle_extension','bilateral','total',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('calf-raise','calves','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hip-thrust','Barbell Hip Thrust','ヒップスラスト','compound','barbell','hinge','bilateral','total',0,'8-12','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hip-thrust','glutes','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hip-thrust','hamstrings','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('hanging-leg-raise','Hanging Leg Raise','ハンギングレッグレイズ','isolation','bodyweight','trunk_flexion','bilateral','total',1,'10-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hanging-leg-raise','abs','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('hanging-leg-raise','obliques','secondary',0.5);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('cable-crunch','Cable Crunch','ケーブルクランチ','isolation','cable','trunk_flexion','bilateral','total',0,'12-20','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('cable-crunch','abs','primary',1);
INSERT OR IGNORE INTO exercises (id,name_en,name_ja,category,equipment,movement_pattern,laterality,load_basis,is_bodyweight,default_rep_range,gh_exercise_type,is_custom) VALUES ('russian-twist','Russian Twist','ロシアンツイスト','isolation','bodyweight','trunk_rotation','bilateral','total',1,'15-30','STRENGTH_TRAINING',0);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('russian-twist','obliques','primary',1);
INSERT OR IGNORE INTO exercise_muscles (exercise_id,muscle_group_id,role,contribution) VALUES ('russian-twist','abs','secondary',0.5);
